"""query rewrite tables and project config pointer

Revision ID: 2384b6753ecc
Revises: 3896c839d8e4
Create Date: 2026-08-24 07:55:07.426384

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2384b6753ecc'
down_revision: str | None = '3896c839d8e4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rewrite_config_versions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rewrite_config_versions', schema=None) as batch_op:
        batch_op.create_index('ix_rewrite_config_project', ['project_id'], unique=False)

    op.create_table('rewrite_feedback',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('proposed_rewrite', sa.Text(), nullable=True),
    sa.Column('edited_rewrite', sa.Text(), nullable=True),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('reason_codes', sa.JSON(), nullable=True),
    sa.Column('original_route', sa.String(length=30), nullable=True),
    sa.Column('rewrite_route', sa.String(length=30), nullable=True),
    sa.Column('model_id', sa.String(length=200), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rewrite_feedback', schema=None) as batch_op:
        batch_op.create_index('ix_rewrite_feedback_project', ['project_id'], unique=False)

    op.create_table('terminology_versions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('terms', sa.JSON(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('terminology_versions', schema=None) as batch_op:
        batch_op.create_index('ix_terminology_project', ['project_id'], unique=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_rewrite_config_id', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('active_rewrite_config_id')

    with op.batch_alter_table('terminology_versions', schema=None) as batch_op:
        batch_op.drop_index('ix_terminology_project')

    op.drop_table('terminology_versions')
    with op.batch_alter_table('rewrite_feedback', schema=None) as batch_op:
        batch_op.drop_index('ix_rewrite_feedback_project')

    op.drop_table('rewrite_feedback')
    with op.batch_alter_table('rewrite_config_versions', schema=None) as batch_op:
        batch_op.drop_index('ix_rewrite_config_project')

    op.drop_table('rewrite_config_versions')
    # ### end Alembic commands ###
